version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: chattydb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:latest
    container_name: chattyredis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
